version: '3.8'

services:
  apt-repo:
    build: .
    container_name: depot-apt
    ports:
      - "80:80"
    volumes:
      # Persister les clés GPG
      - ./.gnupg:/root/.gnupg

      # Persister la configuration du dépôt
      - ./repos/conf:/usr/share/nginx/html/repos/conf

      # Persister les paquets et métadonnées du dépôt
      - ./repos/dists:/usr/share/nginx/html/repos/dists
      - ./repos/pool:/usr/share/nginx/html/repos/pool
      - ./repos/db:/usr/share/nginx/html/repos/db

      # Configuration Nginx
      - ./nginx/repo.conf:/etc/nginx/conf.d/repo.conf:ro

      # script mise à jour deb
      - ./scripts/add-deb.sh:/add-deb.sh
    restart: unless-stopped
