server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html/repos;
    autoindex on;

    # Expose correctement le dépôt avec le bon chemin
    location /repos/ {
        root /usr/share/nginx/html/;
        autoindex on;
    }

    # Bloquer l'accès aux fichiers internes de reprepro
    location ~ /repos/.*/conf {
        deny all;
    }

    location ~ /repos/.*/db {
        deny all;
    }
}
