server {
    listen 80;
    server_name localhost;

    # Chemin vers les fichiers statiques de l'application React
    root /usr/share/nginx/html;
    index index.html;

    # Servir les fichiers statiques
    location / {
        try_files $uri /index.html;
    }

    # Gérer les fichiers dans le dossier static/
    location /static/ {
        alias /usr/share/nginx/html/static/;
    }

    # Gérer les erreurs 404
    error_page 404 /index.html;

    # Gérer les erreurs 500, 502, 503, 504
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
